<Meals@GridLayout>:
	rows: 4
	cols: 7
	canvas:
		Color:
			rgba: 0.5,0.75,0.5,1
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput:
	TextInput: