#:kivy 1.10.0

<GroceryList>:    
    canvas:
    	Color:
    		rgba: 1, 1, 1, 1
    	Rectangle:
    		pos: self.pos
    		size: self.size

    orientation: 'vertical'
    BoxLayout:
        size_hint: 1, .1
        Days:
    BoxLayout:
    	DrawGrid:
    Scatter:
    	size_hint: 1, .15
    	BoxLayout:
        	Recipes:
        		Label:
        			text: 'Pizza Potato'
        	Recipes:
        		Label:
        			text: 'Cookies'
        			

        

    
